import type { Metadata } from "next";
import "./globals.css";
import "highlight.js/styles/github-dark.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Redark",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body className={`antialiased bg-gray-100 text-black`}>
        <div className="bg-white w-full max-w-[1260px] min-h-screen mx-auto container-shadow">
          <Header />
          <div className="flex flex-col md:flex-row gap-6">
            <main className="flex-1 leading-relaxed px-4 py-6">{children}</main>
            <aside className="w-auto md:w-60 lg:w-80">Sidebar</aside>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
